# Generated by Django 4.1.3 on 2022-11-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('curator', 'Curator'), ('admin', 'Admin'), ('student', 'Student')], default='admin', max_length=64),
            preserve_default=False,
        ),
    ]
