# Generated by Django 4.1.3 on 2022-11-01 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='university.course'),
        ),
        migrations.AddField(
            model_name='disciplinecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course'),
        ),
        migrations.AddField(
            model_name='disciplinecourse',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.discipline'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='courses',
            field=models.ManyToManyField(related_name='disciplines', through='university.DisciplineCourse', to='university.course'),
        ),
        migrations.AddField(
            model_name='curatorcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course'),
        ),
        migrations.AddField(
            model_name='curatorcourse',
            name='curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.curator'),
        ),
        migrations.AddField(
            model_name='curator',
            name='courses',
            field=models.ManyToManyField(related_name='curators', through='university.CuratorCourse', to='university.course'),
        ),
        migrations.AddField(
            model_name='curator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
