# Generated by Django 4.1.3 on 2022-11-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='disciplinecourse',
            constraint=models.UniqueConstraint(fields=('course', 'discipline'), name='course_discipline_unique'),
        ),
    ]
